import uuid
import json
import time

class FinancialEnvelope:
    """
    Encapsulates an external task request into a Financial Envelope
    with an ATN Task ID, Solana escrow details, and a transaction signature.
    Also simulates a locking timer for refund logic.
    """
    REFUND_TIMEOUT_SECONDS = 15 * 60 # 15 minutes for simulation

    def __init__(self):
        pass

    def wrap_request(self, external_payload: dict, financial_params: dict) -> dict:
        """
        Wraps an external task request with ATN financial context.
        :param external_payload: The original task request from an external platform (e.g., Claude, Perplexity).
        :param financial_params: Financial parameters (escrow_amount_sol, slashing_penalty_sol, min_sbt_score).
        :return: A dictionary representing the financial envelope.
        """
        atn_task_id = str(uuid.uuid4())
        
        # In a real Solana environment, these would be generated by a wallet/SDK
        # Here, we simulate them as placeholders.
        solana_escrow_address = f"ATNEscrow_{atn_task_id.replace('-', '')[:16]}"
        transaction_signature = f"TxSig_{uuid.uuid4().hex}"

        financial_envelope = {
            "atn_task_id": atn_task_id,
            "solana_escrow_details": {
                "escrow_address": solana_escrow_address,
                "escrow_amount_sol": financial_params.get("escrow_amount_sol", 0.0),
                "slashing_penalty_sol": financial_params.get("slashing_penalty_sol", 0.0),
                "min_sbt_score": financial_params.get("min_sbt_score", 0),
                "transaction_signature": transaction_signature,
                "locked_timestamp": time.time(), # Start of the lock timer
                "status": "escrow_locked",
                "refund_eligible_after": time.time() + self.REFUND_TIMEOUT_SECONDS
            },
            "original_request": external_payload
        }
        return financial_envelope

    def check_for_refund(self, financial_envelope: dict) -> dict:
        """
        Simulates checking if an escrowed task is eligible for refund due to timeout.
        In a real system, this would involve on-chain checks.
        """
        details = financial_envelope["solana_escrow_details"]
        current_time = time.time()

        if details["status"] == "escrow_locked" and current_time > details["refund_eligible_after"]:
            print(f"ATN_Protocol: Task {financial_envelope['atn_task_id']} timed out. Initiating refund process.")
            details["status"] = "refund_initiated"
            # In a real system, this would trigger a Solana transaction to unlock funds.
            details["refund_transaction_id"] = f"RefundTx_{uuid.uuid4().hex}"
        elif details["status"] == "escrow_locked":
            print(f"ATN_Protocol: Task {financial_envelope['atn_task_id']} is still active. Time remaining for delivery: {int(details['refund_eligible_after'] - current_time)} seconds.")
        else:
            print(f"ATN_Protocol: Task {financial_envelope['atn_task_id']} status is {details['status']}, not eligible for timeout refund check.")
        
        return financial_envelope

if __name__ == "__main__":
    print("Financial Envelope module loaded.")
    
    # 模拟一个来自外部的请求 (例如 Claude)
    external_claude_request = {
        "source": "Claude",
        "request_id": "claude-req-123",
        "task": {
            "type": "search_flight_tickets",
            "details": {
                "from": "London",
                "to": "New York",
                "date": "2026-09-15",
                "passengers": 1
            }
        }
    }

    # 模拟 UAAP Schema 中的金融参数
    simulated_financial_params = {
        "escrow_amount_sol": 0.1,
        "slashing_penalty_sol": 0.02,
        "min_sbt_score": 100
    }

    envelope_maker = FinancialEnvelope()
    
    print("\\n--- 封裝跨平台請求 ---")
    wrapped_request_json = envelope_maker.wrap_request(external_claude_request, simulated_financial_params)
    print("被封装后的跨平台请求 JSON 範例:")
    print(json.dumps(wrapped_request_json, indent=4))

    # 模拟超时退款逻辑
    print("\\n--- 模拟超时退款逻辑 ---")
    # 首次检查：任务仍在锁定中，未超时
    updated_envelope = envelope_maker.check_for_refund(wrapped_request_json)
    print(json.dumps(updated_envelope["solana_escrow_details"], indent=4))

    # 模拟时间流逝，使其超过退款截止时间
    print(f"模拟时间流逝 {FinancialEnvelope.REFUND_TIMEOUT_SECONDS + 5} 秒...")
    time.sleep(1) # simulate some time passing, though not the full 15 minutes for actual run
    
    # 为了演示，我们直接修改时间戳以模拟超时
    wrapped_request_json["solana_escrow_details"]["locked_timestamp"] = time.time() - (FinancialEnvelope.REFUND_TIMEOUT_SECONDS + 10)
    wrapped_request_json["solana_escrow_details"]["refund_eligible_after"] = wrapped_request_json["solana_escrow_details"]["locked_timestamp"] + FinancialEnvelope.REFUND_TIMEOUT_SECONDS


    # 再次检查：任务现在应该超时并进入退款状态
    updated_envelope_refunded = envelope_maker.check_for_refund(wrapped_request_json)
    print(json.dumps(updated_envelope_refunded["solana_escrow_details"], indent=4))